#!/bin/bash

##########################################################################
# load-monitor.sh                                                        #
#                                                                        #
# This script reads delay-load info from a file generated by LES and     #
# plots the estimated load in real time.                                 #
# Example: ./load-monitor.sh fname		                                 #
#                                                                        #
# Author: Pantelis A. Frangoudis [pantelis.frangoudis@inria.fr]          #
##########################################################################

# File with delay-load values (2 columns)
DATAFILE=$1

# Window of samples to plot
SAMPLEWIN=10000

# Y-axis
YMAX=2800000
YMIN=0.0

# Create a gnuplot script and execute it. Should end with the reread command.
cat > ./rt-load-plot.gp <<EOF
set title "Path delay calculated from PTPv2 message exchanges"
set key off
set xdata time
set timefmt "%Y-%m-%d,%H:%M:%S"
set xrange [0:$SAMPLEWIN]
set yrange [$YMIN:$YMAX]
set ylabel "Path delay [ns]"
set xlabel "Time"
# Uncomment to hide time from x-axis
set noxtics
set autoscale x
plot '< tail -n $SAMPLEWIN $DATAFILE ' using 1:2 w linespoints
pause 1
reread
EOF

gnuplot ./rt-load-plot.gp

